@startuml
hide circle
skinparam linetype ortho
skinparam shadowing false

entity "SchoolYear" as SchoolYear {
  * schoolYearId : INT <<PK>>
  --
  year : VARCHAR
}

entity "SchoolYearProject" as SchoolYearProject {
  * schoolYearProjectId : INT <<PK>>
  --
 * schoolYearId : INT <<PK,FK>>
 * ProjectId : INT <<PK,FK>>
}

entity "StudentClass" as Class {
  * classId : INT <<PK>>
  --
  name : VARCHAR
  branch : VARCHAR
}

entity "Student" as Student {
  * studentId : VARCHAR <<PK>>
  --
  firstName : VARCHAR
  lastName  : VARCHAR
}

entity "Professor" as Professor {
  * professorId : VARCHAR <<PK>>
  --
  firstName : VARCHAR
  lastName  : VARCHAR
}

entity "StudentClassHistory" as StudentClassHistory {
  * historyId : INT <<PK>>
  --
  studentId : INT <<FK>>
  classId : INT <<FK>>
  schoolYearId : INT <<FK>>
}

entity "Project" as Project {
  * projectId : INT <<PK>>
  --
  title : VARCHAR
  description : TEXT
  githubUrl : VARCHAR
  logoUrl : VARCHAR
  status : VARCHAR
  technology : VARCHAR
  projectType : VARCHAR
}

entity "ProjectStudent" as ProjectStudent {
  * projectStudentId : INT <<PK>>
  --
  * projectId : INT <<PK,FK>>
  * historyId : INT <<PK,FK>>
  --
  role : VARCHAR
}

entity "ProjectSupervisor" as ProjectSupervisor {
  * projectSupervisorId : INT <<PK>>
  --
  * projectId : INT <<PK,FK>>
  * professorId : VARCHAR <<PK,FK>>
  --
  role : VARCHAR
}

SchoolYear "1" -- "n" StudentClassHistory
Class      "1" -- "n" StudentClassHistory
Student    "1" -- "n" StudentClassHistory

Project "1" -- "n" SchoolYearProject
SchoolYear "1" -- "n" SchoolYearProject

Project              "1" -- "n" ProjectStudent
StudentClassHistory  "1" -- "n" ProjectStudent

Project    "1" -- "n" ProjectSupervisor
Professor  "1" -- "n" ProjectSupervisor
@enduml