@startuml
hide circle
skinparam linetype ortho
skinparam shadowing false

entity "SchoolYear" as SchoolYear {
  * school_year_id : INT <<PK>>
  --
  label : VARCHAR
}

entity "Class" as Class {
  * class_id : INT <<PK>>
  --
  name : VARCHAR
  year_level : INT
  branch : VARCHAR
}

entity "Student" as Student {
  * student_id : INT <<PK>>
  --
  first_name : VARCHAR
  last_name  : VARCHAR
  if_name : VARCHAR
}

entity "Professor" as Professor {
  * professor_id : INT <<PK>>
  --
  first_name : VARCHAR
  last_name  : VARCHAR
}

entity "StudentClassHistory" as StudentClassHistory {
  * history_id : INT <<PK>>
  --
  student_id : INT <<FK>>
  class_id : INT <<FK>>
  school_year_id : INT <<FK>>
}

entity "Project" as Project {
  * project_id : INT <<PK>>
  --
  school_year_id : INT <<FK>>
  title : VARCHAR
  description : TEXT
  github_url : VARCHAR
  logo_url : VARCHAR
  status : VARCHAR
  technology : VARCHAR
}

entity "ProjectStudent" as ProjectStudent {
  * project_id : INT <<PK,FK>>
  * history_id : INT <<PK,FK>>
  --
  role : VARCHAR
}

entity "ProjectSupervisor" as ProjectSupervisor {
  * project_id : INT <<PK,FK>>
  * professor_id : INT <<PK,FK>>
  --
  role : VARCHAR
}

SchoolYear "1" -- "n" StudentClassHistory
Class      "1" -- "n" StudentClassHistory
Student    "1" -- "n" StudentClassHistory

SchoolYear "1" -- "n" Project

Project              "1" -- "n" ProjectStudent
StudentClassHistory  "1" -- "n" ProjectStudent

Project    "1" -- "n" ProjectSupervisor
Professor  "1" -- "n" ProjectSupervisor
@enduml
