using Microsoft.EntityFrameworkCore;
using Persistence;
using Persistence.Entities;

namespace WebAPI;

public static class DatabaseInitializer
{
    public static async Task EnsureSchemaAsync(ApplicationDbContext db)
    {
        await db.Database.EnsureCreatedAsync();

        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "Competition" (
                "CompetitionId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "Name" character varying(200) NOT NULL,
                "CompetitionType" character varying(50) NOT NULL,
                "StartDate" date NOT NULL,
                "EndDate" date NULL,
                "PresentationDurationMinutes" integer NOT NULL,
                "BreakDurationMinutes" integer NOT NULL,
                "AllowedClassTypes" character varying(100) NOT NULL,
                "Status" character varying(50) DEFAULT 'Active' NOT NULL,
                "CreatedAtUtc" timestamp with time zone NOT NULL
            );
            """);

        await db.Database.ExecuteSqlRawAsync("""
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_name = 'Competition' AND column_name = 'Status'
                ) THEN
                    ALTER TABLE "Competition" ADD COLUMN "Status" character varying(50) DEFAULT 'Active' NOT NULL;
                END IF;

                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_name = 'Project' AND column_name = 'ApprovalNote'
                ) THEN
                    ALTER TABLE "Project" ADD COLUMN "ApprovalNote" character varying(1000) NULL;
                END IF;

                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_name = 'Project' AND column_name = 'SubmittedAtUtc'
                ) THEN
                    ALTER TABLE "Project" ADD COLUMN "SubmittedAtUtc" timestamp with time zone NULL;
                END IF;

                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_name = 'Project' AND column_name = 'ApprovedAtUtc'
                ) THEN
                    ALTER TABLE "Project" ADD COLUMN "ApprovedAtUtc" timestamp with time zone NULL;
                END IF;

                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_name = 'Project' AND column_name = 'ApprovedByProfessorId'
                ) THEN
                    ALTER TABLE "Project" ADD COLUMN "ApprovedByProfessorId" character varying(128) NULL;
                END IF;

                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_name = 'Project' AND column_name = 'IsExternal'
                ) THEN
                    ALTER TABLE "Project" ADD COLUMN "IsExternal" boolean DEFAULT false NOT NULL;
                END IF;

                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_name = 'Project' AND column_name = 'ExternalSchoolName'
                ) THEN
                    ALTER TABLE "Project" ADD COLUMN "ExternalSchoolName" character varying(200) NULL;
                END IF;

                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_name = 'Project' AND column_name = 'HasConsent'
                ) THEN
                    ALTER TABLE "Project" ADD COLUMN "HasConsent" boolean DEFAULT false NOT NULL;
                END IF;

                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_name = 'Project' AND column_name = 'ConsentConfirmedAtUtc'
                ) THEN
                    ALTER TABLE "Project" ADD COLUMN "ConsentConfirmedAtUtc" timestamp with time zone NULL;
                END IF;

                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_name = 'Project' AND column_name = 'ConsentConfirmedBy'
                ) THEN
                    ALTER TABLE "Project" ADD COLUMN "ConsentConfirmedBy" character varying(200) NULL;
                END IF;

                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_name = 'CompetitionProject' AND column_name = 'HasConsent'
                ) THEN
                    ALTER TABLE "CompetitionProject" ADD COLUMN "HasConsent" boolean DEFAULT false NOT NULL;
                END IF;

                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_name = 'CompetitionProject' AND column_name = 'ConsentConfirmedAtUtc'
                ) THEN
                    ALTER TABLE "CompetitionProject" ADD COLUMN "ConsentConfirmedAtUtc" timestamp with time zone NULL;
                END IF;
            END $$;
            """);

        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "CompetitionProject" (
                "CompetitionId" integer NOT NULL,
                "ProjectId" integer NOT NULL,
                "JoinedAtUtc" timestamp with time zone NOT NULL,
                "Note" character varying(500) NULL,
                CONSTRAINT "PK_CompetitionProject" PRIMARY KEY ("CompetitionId", "ProjectId"),
                CONSTRAINT "FK_CompetitionProject_Competition_CompetitionId"
                    FOREIGN KEY ("CompetitionId") REFERENCES "Competition" ("CompetitionId") ON DELETE CASCADE,
                CONSTRAINT "FK_CompetitionProject_Project_ProjectId"
                    FOREIGN KEY ("ProjectId") REFERENCES "Project" ("ProjectId") ON DELETE CASCADE
            );
            """);

        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "ScheduleSlot" (
                "ScheduleSlotId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "CompetitionId" integer NOT NULL,
                "ProjectId" integer NULL,
                "SlotType" character varying(30) NOT NULL,
                "Date" date NOT NULL,
                "StartTime" time without time zone NOT NULL,
                "DurationMinutes" integer NOT NULL,
                "Title" character varying(200) NOT NULL,
                "Note" character varying(1000) NULL,
                CONSTRAINT "FK_ScheduleSlot_Competition_CompetitionId"
                    FOREIGN KEY ("CompetitionId") REFERENCES "Competition" ("CompetitionId") ON DELETE CASCADE,
                CONSTRAINT "FK_ScheduleSlot_Project_ProjectId"
                    FOREIGN KEY ("ProjectId") REFERENCES "Project" ("ProjectId") ON DELETE SET NULL
            );
            """);

        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "EvaluationCriterion" (
                "CriterionId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "CompetitionId" integer NOT NULL,
                "Name" character varying(150) NOT NULL,
                "Description" character varying(500) NULL,
                "MinScore" integer NOT NULL DEFAULT 0,
                "MaxScore" integer NOT NULL DEFAULT 10,
                "Weight" double precision NOT NULL DEFAULT 1.0,
                "OrderIndex" integer NOT NULL DEFAULT 0,
                CONSTRAINT "FK_EvaluationCriterion_Competition_CompetitionId"
                    FOREIGN KEY ("CompetitionId") REFERENCES "Competition" ("CompetitionId") ON DELETE CASCADE
            );
            """);

        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "JuryMember" (
                "JuryMemberId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "CompetitionId" integer NOT NULL,
                "ProfessorId" character varying(128) NULL,
                "ExternalName" character varying(150) NULL,
                "ExternalEmail" character varying(150) NULL,
                "Role" character varying(50) NOT NULL DEFAULT 'Juror',
                "AddedAtUtc" timestamp with time zone NOT NULL,
                CONSTRAINT "FK_JuryMember_Competition_CompetitionId"
                    FOREIGN KEY ("CompetitionId") REFERENCES "Competition" ("CompetitionId") ON DELETE CASCADE,
                CONSTRAINT "FK_JuryMember_Person_ProfessorId"
                    FOREIGN KEY ("ProfessorId") REFERENCES "Person" ("Id") ON DELETE SET NULL
            );
            """);

        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "ProjectEvaluation" (
                "EvaluationId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "CompetitionId" integer NOT NULL,
                "ProjectId" integer NOT NULL,
                "JuryMemberId" integer NOT NULL,
                "CriterionId" integer NOT NULL,
                "Score" double precision NOT NULL,
                "Note" character varying(2000) NULL,
                "UpdatedAtUtc" timestamp with time zone NOT NULL,
                CONSTRAINT "FK_ProjectEvaluation_Competition_CompetitionId"
                    FOREIGN KEY ("CompetitionId") REFERENCES "Competition" ("CompetitionId") ON DELETE CASCADE,
                CONSTRAINT "FK_ProjectEvaluation_Project_ProjectId"
                    FOREIGN KEY ("ProjectId") REFERENCES "Project" ("ProjectId") ON DELETE CASCADE,
                CONSTRAINT "FK_ProjectEvaluation_JuryMember_JuryMemberId"
                    FOREIGN KEY ("JuryMemberId") REFERENCES "JuryMember" ("JuryMemberId") ON DELETE CASCADE,
                CONSTRAINT "FK_ProjectEvaluation_EvaluationCriterion_CriterionId"
                    FOREIGN KEY ("CriterionId") REFERENCES "EvaluationCriterion" ("CriterionId") ON DELETE CASCADE,
                CONSTRAINT "UQ_ProjectEvaluation" UNIQUE ("CompetitionId", "ProjectId", "JuryMemberId", "CriterionId")
            );
            """);

        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "Invitation" (
                "InvitationId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "Email" character varying(200) NOT NULL,
                "RecipientName" character varying(200) NOT NULL,
                "SchoolName" character varying(200) NULL,
                "TargetRole" character varying(50) NOT NULL,
                "CompetitionId" integer NULL,
                "ProjectId" integer NULL,
                "Token" character varying(128) NOT NULL,
                "Status" character varying(50) NOT NULL DEFAULT 'Pending',
                "CreatedAtUtc" timestamp with time zone NOT NULL,
                "ExpiresAtUtc" timestamp with time zone NOT NULL,
                "AcceptedAtUtc" timestamp with time zone NULL,
                "CreatedByUserId" character varying(100) NULL,
                CONSTRAINT "FK_Invitation_Competition_CompetitionId"
                    FOREIGN KEY ("CompetitionId") REFERENCES "Competition" ("CompetitionId") ON DELETE SET NULL,
                CONSTRAINT "FK_Invitation_Project_ProjectId"
                    FOREIGN KEY ("ProjectId") REFERENCES "Project" ("ProjectId") ON DELETE SET NULL
            );

            CREATE UNIQUE INDEX IF NOT EXISTS "IX_Invitation_Token" ON "Invitation" ("Token");
            """);

        // Ensure every competition has default evaluation criteria so jurors immediately have scoring sliders
        var competitionsWithoutCriteria = await db.Competitions
            .Where(c => !db.EvaluationCriteria.Any(ec => ec.CompetitionId == c.Id))
            .ToListAsync();

        foreach (var comp in competitionsWithoutCriteria)
        {
            db.EvaluationCriteria.AddRange(
                new EvaluationCriterion
                {
                    CompetitionId = comp.Id,
                    Name = "Idee & Innovationsgrad",
                    Description = "Neuheitswert, Problemverständnis und Innovationskraft des Lösungsansatzes",
                    MinScore = 0,
                    MaxScore = 10,
                    Weight = 1.0,
                    OrderIndex = 1
                },
                new EvaluationCriterion
                {
                    CompetitionId = comp.Id,
                    Name = "Technische Umsetzung & Architektur",
                    Description = "Code-Qualität, Funktionsumfang, Stabilität und architektureller Aufbau",
                    MinScore = 0,
                    MaxScore = 10,
                    Weight = 1.5,
                    OrderIndex = 2
                },
                new EvaluationCriterion
                {
                    CompetitionId = comp.Id,
                    Name = "Präsentation & Live-Demo",
                    Description = "Überzeugender Pitch, Struktur, Teamwork und souveräne Beantwortung von Fragen",
                    MinScore = 0,
                    MaxScore = 10,
                    Weight = 1.0,
                    OrderIndex = 3
                }
            );
        }

        if (competitionsWithoutCriteria.Count > 0)
        {
            await db.SaveChangesAsync();
        }
    }
}
